### ISSUE TITLE
Link title, omit link column

### ISSUE THREAD

**Issue by rhersel** [MrReSc/sitemap-table-generator#3]
Issue:
There is no benefit from having the title and link column separated. Putting a link on title, results in more horizontal space, a more intuitive handling and a better look and feel. This would give also more space for the article description, which is currently very small. The author and category columns could also be narrowed to increase the overview. On the other hand there is no drawback, because the real URL would be still visible when hovering at the title.

Change request:
- remove link column
- put that link on the title in title column
- widen description column
- narrow author and category column

**Comment by MrReSc** [comment]
fixed with PR #5
